const $=s=>document.querySelector(s);const files=[];const maxSize=100*1024*1024;let posts=JSON.parse(localStorage.getItem('mod-posts')||'[]');
const input=$('#fileInput'),zone=$('#dropZone'),list=$('#fileList'),form=$('#postForm');
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
function formatSize(bytes){if(bytes<1024)return bytes+' B';if(bytes<1048576)return (bytes/1024).toFixed(1)+' KB';return (bytes/1048576).toFixed(1)+' MB'}
function renderFiles(){list.innerHTML='';files.forEach((file,i)=>{const chip=document.createElement('div');chip.className='file-chip';const icon=file.type.startsWith('image/')?URL.createObjectURL(file):'';chip.innerHTML=`${icon?`<img src="${icon}" alt="">`:'<span class="file-icon">◈</span>'}<span title="${file.name}">${file.name}<small style="display:block;color:var(--muted)">${formatSize(file.size)}</small></span><button class="remove-file" type="button" data-index="${i}" aria-label="Hapus ${file.name}">×</button>`;list.appendChild(chip)});$('#aiHint').textContent=files.length?`${files.length} file siap dideskripsikan secara otomatis.`:'Tambahkan file untuk mendapatkan saran deskripsi otomatis.'}
function addFiles(selected){[...selected].forEach(file=>{if(file.size>maxSize)return toast(`${file.name} melebihi batas 100 MB.`);if(files.length<8)files.push(file)});renderFiles()}
input.addEventListener('change',e=>addFiles(e.target.files));zone.addEventListener('click',e=>{if(e.target!==input)input.click()});['dragenter','dragover'].forEach(ev=>zone.addEventListener(ev,e=>{e.preventDefault();zone.classList.add('dragging')}));['dragleave','drop'].forEach(ev=>zone.addEventListener(ev,e=>{e.preventDefault();zone.classList.remove('dragging')}));zone.addEventListener('drop',e=>addFiles(e.dataTransfer.files));list.addEventListener('click',e=>{if(e.target.dataset.index!==undefined){files.splice(+e.target.dataset.index,1);renderFiles()}});
function smartDescription(){if(!files.length)return 'Tulis catatan singkat atau tambahkan file agar AI dapat membantu.';const types={image:files.filter(f=>f.type.startsWith('image/')).length,video:files.filter(f=>f.type.startsWith('video/')).length,apk:files.filter(f=>f.name.toLowerCase().endsWith('.apk')).length,other:files.filter(f=>!f.type.startsWith('image/')&&!f.type.startsWith('video/')&&!f.name.toLowerCase().endsWith('.apk')).length};let words=[];if(types.image)words.push(`${types.image} gambar visual`);if(types.video)words.push(`${types.video} video`);if(types.apk)words.push(`${types.apk} aplikasi Android`);if(types.other)words.push(`${types.other} berkas pendukung`);return `Kumpulan ${words.join(', ')} yang dibagikan untuk menjelajah, mencoba, dan menemukan sesuatu yang baru. Simpan file ini untuk referensi atau gunakan sesuai kebutuhan.`}
$('#generateButton').addEventListener('click',()=>{const text=smartDescription();const content=$('#content');content.value=content.value?`${content.value}\n\n${text}`:text;$('#saveStatus').textContent='Deskripsi dibuat ✦';toast('Deskripsi AI berhasil dibuat')});
function filePreview(file){return file.type.startsWith('image/')?URL.createObjectURL(file):file.type.startsWith('video/')?URL.createObjectURL(file):''}
function renderPosts(){const query=$('#searchInput').value.toLowerCase();const grid=$('#postGrid');grid.innerHTML='';const shown=posts.filter(p=>(p.title+' '+p.content).toLowerCase().includes(query));$('#emptyState').style.display=shown.length?'none':'block';shown.forEach((p,index)=>{const card=document.createElement('article');card.className='post-card';const media=p.preview?`<${p.kind==='video'?'video':'img'} src="${p.preview}" ${p.kind==='video'?'controls':''} alt="Preview ${p.title}"></${p.kind==='video'?'video':'img'}>`:'<span class="file-icon">✦</span>';card.innerHTML=`<div class="post-media">${media}</div><div class="post-body"><h3>${escapeHtml(p.title)}</h3><p>${escapeHtml(p.content||'Posting tanpa deskripsi.')}</p><div class="post-footer"><span>${escapeHtml(p.author||'Anonymous')} · ${p.files} file</span><button data-copy="${index}">Salin</button></div></div>`;grid.appendChild(card)})}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}$('#searchInput').addEventListener('input',renderPosts);$('#postGrid').addEventListener('click',e=>{if(e.target.dataset.copy!==undefined){navigator.clipboard?.writeText(posts[e.target.dataset.copy].content||'');toast('Deskripsi disalin')}});
form.addEventListener('submit',e=>{e.preventDefault();if(!$('#title').value.trim())return;const first=files[0];posts.unshift({title:$('#title').value.trim(),author:$('#author').value.trim()||'Anonymous',content:$('#content').value.trim()||smartDescription(),files:files.length,kind:first?.type.startsWith('video/')?'video':'image',preview:first?filePreview(first):'',date:Date.now()});localStorage.setItem('mod-posts',JSON.stringify(posts));renderPosts();form.reset();files.length=0;renderFiles();toast('Posting berhasil diterbitkan ✦');location.hash='explore'});form.addEventListener('reset',()=>setTimeout(()=>{files.length=0;renderFiles()},0));$('#themeToggle').addEventListener('click',()=>{document.body.classList.toggle('dark');localStorage.setItem('mod-dark',document.body.classList.contains('dark'))});if(localStorage.getItem('mod-dark')==='true')document.body.classList.add('dark');renderPosts();renderFiles();
