const $=s=>document.querySelector(s), files=[], MAX=100*1024*1024;
const input=$('#fileInput'),list=$('#fileList'),form=$('#postForm');
const configured=window.MOD_SUPABASE_URL&&!window.MOD_SUPABASE_URL.includes('YOUR-')&&window.MOD_SUPABASE_ANON_KEY&&!window.MOD_SUPABASE_ANON_KEY.includes('YOUR_');
const db=configured?window.supabase.createClient(window.MOD_SUPABASE_URL,window.MOD_SUPABASE_ANON_KEY):null;let posts=[];
function toast(m){const e=$('#toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2800)}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function size(n){return n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(1)} MB`}
function kind(f){return f.type?.startsWith('image/')?'Image':f.type?.startsWith('video/')?'Video':f.name.toLowerCase().endsWith('.apk')?'APK':f.name.split('.').pop()?.toUpperCase()||'FILE'}
function renderFiles(){list.innerHTML=files.map((f,i)=>`<div class="file-chip"><span class="file-icon">${kind(f).slice(0,3)}</span><span title="${esc(f.name)}">${esc(f.name)}<small>${size(f.size)} · ${kind(f)}</small></span><button class="remove-file" data-i="${i}" type="button">×</button></div>`).join('');$('#aiHint').textContent=files.length?`${files.length} file siap diunggah.`:'Tambahkan file untuk mendapatkan saran deskripsi otomatis.'}
function addFiles(listing){for(const f of Array.from(listing||[])){if(f.size<=MAX&&files.length<8)files.push(f);else toast(`${f.name} terlalu besar atau jumlah file sudah maksimal.`)}renderFiles()}
input.onchange=e=>{addFiles(e.target.files);input.value=''};$('#dropZone').onclick=e=>{if(e.target!==input)input.click()};['dragenter','dragover'].forEach(x=>$('#dropZone').addEventListener(x,e=>{e.preventDefault();$('#dropZone').classList.add('dragging')}));['dragleave','drop'].forEach(x=>$('#dropZone').addEventListener(x,e=>{e.preventDefault();$('#dropZone').classList.remove('dragging')}));$('#dropZone').ondrop=e=>addFiles(e.dataTransfer.files);list.onclick=e=>{if(e.target.dataset.i!==undefined){files.splice(+e.target.dataset.i,1);renderFiles()}};
function description(){if(!files.length)return'Tulis catatan singkat agar posting lebih informatif.';const a=files.map(kind).reduce((o,k)=>(o[k]=(o[k]||0)+1,o),{});return`Posting ini berisi ${Object.entries(a).map(([k,v])=>`${v} ${k}`).join(', ')}. Temukan, gunakan, dan bagikan file ini sesuai kebutuhan.`}
$('#generateButton').onclick=()=>{$('#content').value=$('#content').value+($('#content').value?'\n\n':'')+description();toast('Deskripsi otomatis dibuat ✦')};
async function load(){if(!db){posts=JSON.parse(localStorage.getItem('mod-posts')||'[]');return render()}const {data,error}=await db.from('posts').select('*,post_files(*)').order('created_at',{ascending:false});if(error){toast('Gagal memuat posting dari cloud');return}posts=data||[];render()}
function media(p){const f=p.post_files?.find(x=>x.mime_type?.startsWith('image/')||x.mime_type?.startsWith('video/'));return f?`<div class="post-media"><${f.mime_type.startsWith('video/')?'video':'img'} src="${esc(f.public_url)}" ${f.mime_type.startsWith('video/')?'controls':''} alt="${esc(p.title)}"></${f.mime_type.startsWith('video/')?'video':'img'}></div>`:'<div class="post-media"><span class="file-icon">✦</span></div>'}
function render(){const q=$('#searchInput').value.toLowerCase(),shown=posts.filter(p=>`${p.title} ${p.description} ${p.author}`.toLowerCase().includes(q));$('#postGrid').innerHTML=shown.map(p=>`<article class="post-card">${media(p)}<div class="post-body"><h3>${esc(p.title)}</h3><p>${esc(p.description||'Posting tanpa deskripsi.')}</p><div class="post-footer"><span>${esc(p.author||'Anonymous')} · ${(p.post_files||[]).length} file</span><button type="button" data-id="${p.id}">Selengkapnya</button></div></div></article>`).join('');$('#emptyState').style.display=shown.length?'none':'block'}
function openDetail(id){const p=posts.find(x=>String(x.id)===String(id));if(!p)return;const attachments=(p.post_files||[]).map(f=>`<a class="download-file" href="${esc(f.public_url)}" download="${esc(f.file_name)}" target="_blank" rel="noopener"><span>↧</span><strong>${esc(f.file_name)}</strong><small>${kind({name:f.file_name,type:f.mime_type})} · ${size(f.file_size)}</small></a>`).join('');const preview=(p.post_files||[]).find(f=>f.mime_type?.startsWith('image/')||f.mime_type?.startsWith('video/'));$('#modalBody').innerHTML=`<div class="modal-header"><span class="eyebrow">Full story</span><h2>${esc(p.title)}</h2><div class="modal-meta">${esc(p.author||'Anonymous')} · ${new Date(p.created_at).toLocaleDateString('id-ID')}</div></div><div class="modal-body">${preview?`<${preview.mime_type.startsWith('video/')?'video':'img'} src="${esc(preview.public_url)}" ${preview.mime_type.startsWith('video/')?'controls':''}></${preview.mime_type.startsWith('video/')?'video':'img'}>`:''}<div class="modal-text">${esc(p.description||'Tidak ada deskripsi.').replace(/\n/g,'<br>')}</div>${attachments?`<h3>File terlampir</h3><div class="download-list">${attachments}</div>`:''}</div>`;$('#detailModal').classList.remove('hidden');$('#detailModal').setAttribute('aria-hidden','false')}
$('#postGrid').onclick=e=>{const b=e.target.closest('[data-id]');if(b)openDetail(b.dataset.id)};function close(){const m=$('#detailModal');m.classList.add('hidden');m.setAttribute('aria-hidden','true')}$('#closeModal').onclick=close;$('#detailModal').onclick=e=>{if(e.target.dataset.close)close()};document.onkeydown=e=>{if(e.key==='Escape')close()};$('#searchInput').oninput=render;
form.onsubmit=async e=>{e.preventDefault();if(!$('#title').value.trim()||!files.length&&!$('#content').value.trim())return toast('Isi judul dan deskripsi atau lampirkan file.');$('#publishButton').disabled=true;try{if(!db){const old=JSON.parse(localStorage.getItem('mod-posts')||'[]');old.unshift({id:crypto.randomUUID(),title:$('#title').value,author:$('#author').value||'Anonymous',description:$('#content').value||description(),post_files:[]});localStorage.setItem('mod-posts',JSON.stringify(old));toast('Mode demo tersimpan lokal');return}const post={title:$('#title').value.trim(),author:$('#author').value.trim()||'Anonymous',description:$('#content').value.trim()||description()};const {data,error}=await db.from('posts').insert(post).select().single();if(error)throw error;const rows=[];for(const f of files){const path=`${data.id}/${crypto.randomUUID()}-${f.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const up=await db.storage.from('mod-files').upload(path,f,{contentType:f.type||'application/octet-stream'});if(up.error)throw up.error;const publicUrl=db.storage.from('mod-files').getPublicUrl(path).data.publicUrl;rows.push({post_id:data.id,file_name:f.name,mime_type:f.type||'application/octet-stream',file_size:f.size,storage_path:path,public_url:publicUrl})}if(rows.length){const r=await db.from('post_files').insert(rows);if(r.error)throw r.error}toast('Posting berhasil dipublikasikan ✦');form.reset();files.length=0;renderFiles();await load();location.hash='explore'}catch(err){toast(`Gagal: ${err.message||'periksa konfigurasi Supabase'}`)}finally{$('#publishButton').disabled=false}};
$('#themeToggle').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('mod-dark',document.body.classList.contains('dark'))};if(localStorage.getItem('mod-dark')==='true')document.body.classList.add('dark');if(!configured)$('#saveStatus').textContent='Demo mode · konfigurasi Supabase diperlukan';renderFiles();load();
